uploads = []
generated = []

[[outputs]]
id = "KLAjYb2pIT70__wA1rtEF"
uri = "file://break-buddy-project.zip"
type = "unspecified"
title = "Break Buddy — código fuente"

[[outputs]]
id = "UNxyAp73U5L8cOS-RfpBw"
uri = "file://break-buddy-review.zip"
type = "unspecified"
title = "break-buddy-review.zip"

[[outputs]]
id = "DC_cRGqHNGgUJSpdqzURg"
uri = "file://break-buddy-audit.zip"
type = "unspecified"
title = "break-buddy-audit.zip"

[[outputs]]
id = "z1uTdxB9U_fyMsq__vT9J"
uri = "file://break-buddy-eval.zip"
type = "unspecified"
title = "Break Buddy — código fuente para evaluación"
